# Pf8 only made calls for QC pass samples?

In [2]:
import pandas as pd

In [3]:
pf8 = pd.read_csv("Pf8_drug_resistance_marker_genotypes.tsv", sep = "\t")

print(pf8.columns)

pf8.head(3)

Index(['Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]',
       'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call'],
      dtype='object')

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call
0,FP0008-C,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
1,FP0009-C,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,Y,VD,D,T,NaN,0,0
2,FP0010-CW,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0

In [4]:
vmp = pd.read_csv("merged__px1_1222_1701_1705+primer2_20040_20060+primer1_20000_20020+mdr1_86_1034_1042_1246+kelch13_349_726+dhps_436_437_540_581_613+dhfr_51_59_108_164+cytb_133_268_283_284+csp_1_200_274_397+crt_75_76_93_97_101_145_218_220_271_326_343_350_352.tsv", sep = "\t")

print(vmp.columns)

vmp.head(3)

Index(['sample_id', 'px1_haplotype', 'px1_ns_changes', 'px1_1222', 'px1_1701',
       'px1_1705', 'primer2_haplotype', 'primer2_20040_20060',
       'primer1_haplotype', 'primer1_20000_20020', 'mdr1_haplotype',
       'mdr1_ns_changes', 'mdr1_86', 'mdr1_1034', 'mdr1_1042', 'mdr1_1246',
       'kelch13_haplotype', 'kelch13_ns_changes', 'dhps_haplotype',
       'dhps_ns_changes', 'dhps_436', 'dhps_437', 'dhps_540', 'dhps_581',
       'dhps_613', 'dhfr_haplotype', 'dhfr_ns_changes', 'dhfr_51', 'dhfr_59',
       'dhfr_108', 'dhfr_164', 'cytb_haplotype', 'cytb_ns_changes', 'cytb_133',
       'cytb_268', 'cytb_283', 'cytb_284', 'csp_haplotype', 'csp_ns_changes',
       'crt_haplotype', 'crt_ns_changes', 'crt_75', 'crt_76', 'crt_93',
       'crt_97', 'crt_101', 'crt_145', 'crt_218', 'crt_220', 'crt_271',
       'crt_326', 'crt_343', 'crt_350', 'crt_352', 'crt_353', 'crt_356',
       'crt_367', 'crt_371', 'coronin_haplotype', 'coronin_ns_changes',
       'coronin_50', 'coronin_100', 'coronin_107', 'PF3D7_0709000_haplotype',
       'PF3D7_0709000_ns_changes', 'PF3D7_0709000_72', 'PF3D7_0709000_74'],
      dtype='object')

,sample_id,px1_haplotype,px1_ns_changes,px1_1222,px1_1701,px1_1705,primer2_haplotype,primer2_20040_20060,primer1_haplotype,primer1_20000_20020,...,crt_371,coronin_haplotype,coronin_ns_changes,coronin_50,coronin_100,coronin_107,PF3D7_0709000_haplotype,PF3D7_0709000_ns_changes,PF3D7_0709000_72,PF3D7_0709000_74
0,FP0008-C,"L,M,D",NaN,L,M,D,-,-,-,-,...,I/R,"G,R,E",NaN,G,R,E,"C,[I/M]",M74[I/M],C,I/M
1,FP0009-C,"L,M,D",NaN,L,M,D,-,-,-,-,...,I,"G,R,E",NaN,G,R,E,"C,I",M74I,C,I
2,FP0010-CW,"L,M,D",NaN,L,M,D,-,-,-,-,...,I/R,"G,R,E",NaN,G,R,E,"C,[I/M]",M74[I/M],C,I/M

In [5]:
merged = pf8.merge(vmp, left_on = "Sample", right_on = "sample_id", how = "left")

In [6]:
merged[["crt_72[C]", "PF3D7_0709000_72"]].value_counts()

crt_72[C]  PF3D7_0709000_72
C          C                   23953
S          S                     402
-          -                      34
S,C        S/C                     6
C,Y        C/Y                     5
C,S        C/S                     5
C          !                       2
Y          Y                       2
Name: count, dtype: int64

In [7]:
merged[["crt_74[M]", "PF3D7_0709000_74"]].value_counts()

crt_74[M]  PF3D7_0709000_74
I          I                   11883
M          M                   11316
I,M        I/M                   608
M,I        M/I                   543
-          -                      52
I,M        I/!                     4
M          !                       2
M,I        M/!                     1
Name: count, dtype: int64

In [8]:
merged[["crt_75[N]", "crt_75"]].value_counts()

crt_75[N]  crt_75
N          N         11205
E          E         11017
D          D           839
E,N        E/N         588
N,E        N/E         523
E,D        E/D          71
D,E        D/E          62
-          -            52
N,D        N/D          19
D,N        D/N           9
E,K        E/K           7
E,N        D/K           6
E,N*       E/N           3
N,E*       N/E           3
K          K             2
N,E        K/D           2
K,E        K/E           1
Name: count, dtype: int64

In [10]:
merged[["crt_76[K]", "crt_76"]].value_counts()

crt_76[K]  crt_76
T          T         12379
K          K         10767
T,K        T/K         607
K,T        K/T         550
T          *            53
-          -            48
T,Q        T/Q           2
K          K/!           1
T,Q        K/P           1
T,Q*       T/Q           1
Name: count, dtype: int64

In [11]:
merged[["crt_93[T]", "crt_93"]].value_counts()

crt_93[T]  crt_93
T          T         23301
S          S           944
S,T        S/T          77
T,S        T/S          54
-          -            28
I          I             2
S,L        S/L           1
T,I        T/I           1
T,T        T             1
Name: count, dtype: int64

In [13]:
merged[["crt_97[H]", "crt_97"]].value_counts()

crt_97[H]  crt_97
H          H         23955
Y          Y           198
Q          Q           108
L          L            60
-          -            31
H,Y        H/Y          25
Y,H        Y/H          11
H,L        H/L           6
L,H        L/H           5
H,Q        H/Q           3
H,H        H             3
Q,H        Q/H           3
Y,Y        Y             1
Name: count, dtype: int64

In [14]:
merged[["crt_218[I]", "crt_218"]].value_counts()

crt_218[I]  crt_218
I           I          23087
-           -            707
F           F            552
I,F         I/F           39
F,I         F/I           24
Name: count, dtype: int64

In [15]:
merged[["crt_220[A]", "crt_220"]].value_counts()

crt_220[A]  crt_220
S           S          11676
A           A          10609
-           -           1108
A,S         A/S          574
S,A         S/A          430
A,A         A              9
A,T         A/T            1
S,F         S/F            1
S,S         S              1
Name: count, dtype: int64

In [16]:
merged[["crt_271[Q]", "crt_271"]].value_counts()

crt_271[Q]  crt_271
E           E          11902
Q           Q          11285
Q,E         Q/E          535
E,Q         E/Q          491
-           -            189
Q,Q         Q              3
E,          E/!            2
Q           L/Q            1
Q,          Q/!            1
Name: count, dtype: int64

In [17]:
merged[["crt_326[N]", "crt_326"]].value_counts()

crt_326[N]  crt_326
N           N          17537
S           S           5772
D           D            423
-           -            372
N,S         N/S          142
S,N         S/N          131
N           -             20
D,N         D/N            8
N,D         N/D            3
S           -              1
Name: count, dtype: int64

In [20]:
merged[["crt_353[G]", "crt_353"]].value_counts()

crt_353[G]  crt_353
G           G          24276
V           V             87
-           -             29
G,V         G/V            9
V,G         V/G            4
G,D         G/D            1
G           G/S            1
            -              1
G,G         G              1
Name: count, dtype: int64

In [21]:
merged[["crt_356[I]", "crt_356"]].value_counts()

crt_356[I]  crt_356
I           I          14846
T           T           8286
L           L            435
I,T         I/T          368
T,I         T/I          364
-           -             98
I,L         I/L            6
L,I         L/I            6
Name: count, dtype: int64

In [22]:
merged[["crt_371[R]", "crt_371"]].value_counts()

crt_371[R]  crt_371
R           R          11954
I           I          11047
R,I         R/I          661
I,R         I/R          584
-           -             87
T           T             72
T,R         T/R            3
I,T         I/T            1
Name: count, dtype: int64

In [24]:
merged[["dhfr_51[N]", "dhfr_51"]].value_counts()

dhfr_51[N]  dhfr_51
I           I          18360
N           N           4029
I,N         I/N          977
N,I         N/I          746
-           -            297
Name: count, dtype: int64

In [25]:
merged[["dhfr_59[C]", "dhfr_59"]].value_counts()

dhfr_59[C]  dhfr_59
R           R          20722
C           C           2034
R,C         R/C          828
C,R         C/R          498
-           -            323
Y,R         Y/R            2
R,Y         R/Y            1
Y,C         Y/C            1
Name: count, dtype: int64

In [26]:
merged[["dhfr_108[S]", "dhfr_108"]].value_counts()

dhfr_108[S]  dhfr_108
N            N           21962
S            S            1215
N,S          N/S           471
-            -             414
S,N          S/N           344
N            -               2
N,T          N/T             1
Name: count, dtype: int64

In [27]:
merged[["dhfr_164[I]", "dhfr_164"]].value_counts()

dhfr_164[I]  dhfr_164
I            I           19105
L            L            4690
-            -             269
I,L          I/L           175
L,I          L/I           167
I            I/!             1
M            M               1
M,I          M/I             1
Name: count, dtype: int64

In [29]:
merged[["dhps_436[S]", "dhps_436"]].value_counts()

dhps_436[S]  dhps_436
S            S           16147
A            A            5564
A,S          A/S          1122
S,A          S/A           890
-            -             332
F            F              93
H            H              27
C            C              25
A,F          A/F            23
Y            Y              20
S,F          S/F            20
A,Y          A/Y            16
F,A          F/A            14
S,H          S/H            14
F,A          S/V            13
S,C          S/C            12
F,S          F/S            12
H,S          H/S            11
Y,S          Y/S             8
Y,A          Y/A             8
             S/D             6
C,S          C/S             4
S,Y          S/Y             4
C,A          C/A             3
A,F*         A/F             3
F,A*         F/A             2
A,V          A/V             1
A,H*         A/H             1
A,A          A               1
S            S/K             1
F,C          F/C             1
S            S/!             1
H,A*         H/A             1
H,F          H/F             1
S,S          S               1
S,L          S/L             1
S,H*         S/H             1
S,G*         S/G             1
S,D*         S/D             1
S,V          S/V             1
Y,A*         Y/A             1
Y,F          Y/F             1
Name: count, dtype: int64

In [30]:
merged[["dhps_437[G]", "dhps_437"]].value_counts()

dhps_437[G]  dhps_437
G            G           19268
A            A            3601
G,A          G/A           686
A,G          A/G           582
-            -             270
G            G/!             1
             G/N             1
Name: count, dtype: int64

In [31]:
merged[["dhps_540[K]", "dhps_540"]].value_counts()

dhps_540[K]  dhps_540
K            K           12846
E            E            7536
N            N            2747
E,K          E/K           395
-            -             363
K,E          K/E           327
N,E          N/E            62
E,N          E/N            57
N,K          N/K            33
K,N          K/N            13
Y            Y               9
E,N*         E/N             5
N,E          K/D             4
N,E*         N/E             3
K,Y          K/Y             2
K,K          K               2
Y,K          Y/K             2
K,D*         K/D             1
K            I               1
             R               1
Name: count, dtype: int64

In [32]:
merged[["dhps_581[A]", "dhps_581"]].value_counts()

dhps_581[A]  dhps_581
A            A           18693
G            G            4798
-            -             365
G,A          G/A           281
A,G          A/G           266
G,G          G               4
A,A          A               1
A            A/!             1
Name: count, dtype: int64

In [33]:
merged[["dhps_613[A]", "dhps_613"]].value_counts()

dhps_613[A]  dhps_613
A            A           22744
S            S             665
A,S          A/S           365
-            -             305
S,A          S/A           252
T            T              54
T,A          T/A            13
A,T          A/T            10
A,V          A/V             1
Name: count, dtype: int64

In [34]:
merged[["mdr1_86[N]", "mdr1_86"]].value_counts()

mdr1_86[N]  mdr1_86
N           N          21139
Y           Y           1895
N,Y         N/Y          598
Y,N         Y/N          438
-           -            334
N,F         N/F            2
N           K/N            1
N,G         N/G            1
N,I         N/I            1
Name: count, dtype: int64

In [36]:
merged[["mdr1_1034[S]", "mdr1_1034"]].value_counts()

mdr1_1034[S]  mdr1_1034
S             S            23122
-             -             1221
C             C               51
I             I               10
I,S           I/S              2
C,S           C/S              1
S,C           S/C              1
S,S           S                1
Name: count, dtype: int64

In [37]:
merged[["mdr1_1042[N]", "mdr1_1042"]].value_counts()

mdr1_1042[N]  mdr1_1042
N             N            22894
-             -             1077
D             D              381
N             -               46
D,N           D/N              6
N,D           N/D              5
Name: count, dtype: int64

In [39]:
merged[["mdr1_1246[D]", "mdr1_1246"]].value_counts()

mdr1_1246[D]  mdr1_1246
D             D            22695
-             -              775
Y             Y              589
D,Y           D/Y            194
Y,D           Y/D            140
D             -               15
              G                1
Name: count, dtype: int64

In [40]:
# merged[["crt_333[T]", "crt_333"]].value_counts()
# merged[["exo_415[E]", "exo_415[E]"]].value_counts()
# merged[["arps10_127-128[VD]", "arps10_127-128[VD]"]].value_counts()
# merged[["fd_193[D]", "fd_193[D]"]].value_counts()
# merged[["mdr2_484[T]", "mdr2_484[D]"]].value_counts()
# merged[["dhfr_16[N]", "dhfr_16"]].value_counts()
# merged[["dhfr_306[S]", "dhfr_306"]].value_counts()
# merged[["mdr1_184[Y]", "mdr1_184"]].value_counts()
# merged[["mdr1_1226[F]", "mdr1_1226"]].value_counts()